In [37]:
import pandas as pd

In [38]:
df= pd.read_csv(r"C:/Users/feggi/Downloads/Customer_Sales_2000_Rows_Portfolio_Project.csv")

In [39]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,City,Purchase_Date,Product_Category,Quantity,Unit_Price,Total_Sales,Payment_Method
0,C0001,Natalie Taylor,Female,23.0,Port Harcourt,2025-03-19,Groceries,7,135.61,949.27,Cash
1,C0002,Benjamin Wright,Male,50.0,Lagos,2025-03-25,Home & Living,2,359.87,719.74,Cash
2,C0003,Hannah Taylor,Male,35.0,Ibadan,2025-01-13,Electronics,1,423.74,423.74,Transfer
3,C0004,Mary Wright,Female,21.0,Port Harcourt,2025-02-20,Fashion,7,324.24,2269.68,CASH
4,C0005,William Lee,Male,45.0,Ibadan,2025-01-07,Groceries,6,209.98,1259.88,Card

In [40]:
#CHECKING FOR MISSING VALUES
df.columns[df.isnull().any()].tolist()

['Age']

In [41]:
df.dtypes

Customer_ID          object
Customer_Name        object
Gender               object
Age                 float64
City                 object
Purchase_Date        object
Product_Category     object
Quantity              int64
Unit_Price          float64
Total_Sales         float64
Payment_Method       object
dtype: object

In [42]:
#Filling The Missing cells with 'null'
df['Age'] = df['Age'].fillna('Missing')

In [43]:
df.columns[df.isnull().any()].tolist()

[]

In [44]:
df['Payment_Method'] = df['Payment_Method'].str.capitalize()

In [45]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,City,Purchase_Date,Product_Category,Quantity,Unit_Price,Total_Sales,Payment_Method
0,C0001,Natalie Taylor,Female,23.0,Port Harcourt,2025-03-19,Groceries,7,135.61,949.27,Cash
1,C0002,Benjamin Wright,Male,50.0,Lagos,2025-03-25,Home & Living,2,359.87,719.74,Cash
2,C0003,Hannah Taylor,Male,35.0,Ibadan,2025-01-13,Electronics,1,423.74,423.74,Transfer
3,C0004,Mary Wright,Female,21.0,Port Harcourt,2025-02-20,Fashion,7,324.24,2269.68,Cash
4,C0005,William Lee,Male,45.0,Ibadan,2025-01-07,Groceries,6,209.98,1259.88,Card

In [46]:
df['City'] = df['City'].replace(['LAGOS','lAGOS'], 'Lagos')

In [47]:
df['City'] = df['City'].replace(['PH'], 'Port Harcourt')

CHANGING DATE FORMAT

In [55]:
df["Purchase_Date"]=pd.to_datetime(df["Purchase_Date"], format="mixed").dt.strftime("%d-%m-%y")

In [56]:
df.tail()

,Customer_ID,Customer_Name,Gender,Age,City,Purchase_Date,Product_Category,Quantity,Unit_Price,Total_Sales,Payment_Method
1995,C1996,William Allen,Male,48.0,Port Harcourt,28-05-25,Electronics,10,405.58,4055.80,Cash
1996,C1997,Victoria Allen,Male,44.0,Abuja,22-06-25,Electronics,4,327.66,1310.64,Card
1997,C1998,Natalie Adams,Male,58.0,Lagos,26-06-25,Home & Living,2,445.67,891.34,Cash
1998,C1999,David Adams,Female,22.0,Lagos,01-01-25,Home & Living,1,115.09,115.09,Card
1999,C2000,Joseph Robinson,Male,34.0,Lagos,22-04-25,Groceries,6,407.09,2442.54,Card

RECALCULATING TOTAL SALES COLUMN

In [57]:
df['Total_Sales']=df['Quantity']* df['Unit_Price']

In [62]:
import numpy as np
errors_checking = df[~np.isclose(df['Quantity']* df['Unit_Price'], df['Total_Sales'], equal_nan=True)]
print(f"here are the incorrect values: {errors_checking}")

here are the incorrect values: Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, City, Purchase_Date, Product_Category, Quantity, Unit_Price, Total_Sales, Payment_Method]
Index: []

In [63]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,City,Purchase_Date,Product_Category,Quantity,Unit_Price,Total_Sales,Payment_Method
0,C0001,Natalie Taylor,Female,23.0,Port Harcourt,19-03-25,Groceries,7,135.61,949.27,Cash
1,C0002,Benjamin Wright,Male,50.0,Lagos,25-03-25,Home & Living,2,359.87,719.74,Cash
2,C0003,Hannah Taylor,Male,35.0,Ibadan,13-01-25,Electronics,1,423.74,423.74,Transfer
3,C0004,Mary Wright,Female,21.0,Port Harcourt,20-02-25,Fashion,7,324.24,2269.68,Cash
4,C0005,William Lee,Male,45.0,Ibadan,07-01-25,Groceries,6,209.98,1259.88,Card